services:
  mysql:
    image: mysql:8
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"
    volumes:
#      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./docker/mysql/data:/var/lib/mysql
      - ./mysql-inventory:/var/lib/mysql
      - ./docker/mysql-inventory/init.sql:/docker-entrypoint-initdb.d/init.sql
